version: '3.1'

services:
  fbgz_proxy:
    image: fbgz_proxy
    build:
      context: ./fbgz_proxy
    volumes:
      - ./fbgz_proxy/www:/srv/www
      - ./fbgz_proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80